version: '3'

services:
  app:
    image: juanoliveira0101/lab4:latest
    container_name: webacademydemo
    restart: always
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production